# Generated by Django 3.2.9 on 2021-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTAapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='upload',
            field=models.FileField(default='None', upload_to='uploads/'),
        ),
    ]
