# Generated by Django 3.2.9 on 2021-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTAapp', '0003_alter_sample_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
